---
# This playbook deploys the whole application stack in this site.

- name: Install Zabbix 3
  hosts: zabbix
  remote_user: root

  roles:
    - sardpost.zabbix3_server
      zabbix_url: zabbix.example.com
      zabbix_version: 3.0
      database_type: mysql
      database_type_long: mysql
      server_dbuser: zabbix-server
      server_dbpassword: zabbix-server
