---
# task file for postgresql

- name: set the correct delegated_dbhost (to support postgres db deployment on a remote dbhost)
  set_fact:
    delegated_dbhost: "{{server_dbhost if (server_dbhost != 'localhost') else inventory_hostname}}"

- name: "PostgreSQL | Create database"
  postgresql_db: name={{ server_dbname }}
                 state=present
  sudo: yes
  sudo_user: postgres
  delegate_to: "{{delegated_dbhost}}"
  when: zabbix_database_creation
  tags:
    - zabbix-server
    - database

- name: "PostgreSQL | Create database user"
  postgresql_user: db={{ server_dbname }}
                   name={{ server_dbuser }}
                   password={{ server_dbpassword }}
                   priv=ALL
                   state=present
  sudo: yes
  sudo_user: postgres
  delegate_to: "{{delegated_dbhost}}"
  when: zabbix_database_creation
  tags:
    - zabbix-server
    - database

- name: "PostgreSQL | Importing schema file"
  shell: "cd {{ datafiles_path }} && psql -h '{{ server_dbhost }}' -U '{{ server_dbuser }}' -d '{{ server_dbname }}' -f schema.sql && touch /etc/zabbix/schema.done"
  args:
    creates: /etc/zabbix/schema.done
  environment:
    PGPASSWORD: '{{ server_dbpassword }}'
  when: zabbix_database_sqlload
  tags:
    - zabbix-server
    - database

- name: "PostgreSQL | Importing images file"
  shell: "cd {{ datafiles_path }} && psql -h '{{ server_dbhost }}' -U '{{ server_dbuser }}' -d '{{ server_dbname }}' -f images.sql && touch /etc/zabbix/images.done"
  args:
    creates: /etc/zabbix/images.done
  environment:
    PGPASSWORD: '{{ server_dbpassword }}'
  when: zabbix_database_sqlload
  tags:
    - zabbix-server
    - database

- name: "PostgreSQL | Importing data file"
  shell: "cd {{ datafiles_path }} && psql -h '{{ server_dbhost }}' -U '{{ server_dbuser }}' -d '{{ server_dbname }}' -f data.sql && touch /etc/zabbix/data.done"
  args:
    creates: /etc/zabbix/data.done
  environment:
    PGPASSWORD: '{{ server_dbpassword }}'
  when: zabbix_database_sqlload
  tags:
    - zabbix-server
    - database

